# Prometheus Configuration untuk MLflow Sales Forecasting Model Monitoring
# Fixed version - Compatible dengan Prometheus 3.2.1

global:
  scrape_interval: 15s      # Scrape targets every 15 seconds
  evaluation_interval: 15s  # Evaluate rules every 15 seconds
  external_labels:
    monitor: 'mlflow-sales-forecasting-monitor'
    environment: 'development'

# Alertmanager configuration (optional untuk production)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Scrape configuration - disesuaikan dengan setup MLflow existing
scrape_configs:
  
  # === JOB 1: PROMETHEUS SELF-MONITORING ===
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics
    
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance_type
        replacement: 'prometheus-server'

  # === JOB 2: MLFLOW SALES FORECASTING MODEL EXPORTER ===
  # Ini yang WORKING (sudah UP)
  - job_name: 'mlflow-sales-forecasting-exporter'
    static_configs:
      - targets: ['localhost:8000']  # prometheus_exporter.py port
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    
    relabel_configs:
      - source_labels: [__address__]
        target_label: service_type
        replacement: 'mlflow-sales-forecasting-exporter'
      - target_label: model_name
        replacement: 'sales-forecasting'
      - target_label: model_version
        replacement: '1.0.0'
    
    honor_labels: true

  # === REMOVED: MLflow Model Server Health Check ===
  # Reason: /ping returns JSON, not Prometheus metrics
  # Health monitoring sudah dilakukan di prometheus_exporter.py
  
  # === REMOVED: MLflow Tracking Server Health Check ===
  # Reason: / returns HTML, not Prometheus metrics  
  # Health monitoring sudah dilakukan di prometheus_exporter.py